# Generated by Django 3.2.5 on 2021-07-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=3)),
                ('department', models.CharField(choices=[('Programmer', 'Programmer'), ('SEO', 'SEO'), ('HR', 'HR')], max_length=10)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emanagement2.employeesalary')),
            ],
        ),
    ]
